### ISSUE TITLE
Aspect-unique CRIT bonuses are not properly applied

### ISSUE THREAD

**Issue by jktrn** [jktrn/abystare#50]
e.g. the character Nahida has a passive "Awakening Elucidated" that gives bonus CRIT Rate to "Tri-Karma Purification", but the CRIT Rate bonus goes unimplemented. We might need a blanket solution.

**Comment by nilocnus** [comment]
Fixed. Any related problems that require bonus stats to be included within the calculation (such as crit damage) can follow the same structure to be resolved
